server:
  port: 8090
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/981222/springcloud.git
          search-paths: config
          username: 985523426@qq.com
          password: 981222fang
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/